---

- name: (efs) Install packages
  yum:
    name: rpm-build
    state: present

- name: (efs) Clone AWS efs-utils
  git:
    repo: https://github.com/aws/efs-utils.git
    dest: '{{ workspace }}/efs-utils'

- name: (efs) Build AWS efs-utils
  make:
    chdir: '{{ workspace }}/efs-utils'
    target: rpm

- name: (efs) Find RPM file
  find:
    path: '{{ workspace }}/efs-utils/build'
    pattern: '*.rpm'
  register: rpm_files

- name: (efs) Install AWS efs-utils
  yum:
    name: '{{ rpm_files.files[0].path }}'
    state: present

- name: (efs) Create mount directory
  file:
    path: '{{ data_file | dirname }}'
    state: directory
    mode: a+rw

- name: (efs) Append to fstab file
  lineinfile:
    path: /etc/fstab
    line: '{{ efs_dns_name }}:/ {{ data_file | dirname }} efs _netdev 0 0'

- name: (efs) Mount disks
  command: mount -a
  args:
    warn: no

- name: (efs) Get the name of the mount unit
  shell: systemctl list-units --type=mount | grep {{ data_file | dirname }} | awk '{print $1}'
  register: efs_mount_unit