---

- name: (failover) Install python3
  yum:
    name: python3
    state: present

- name: (failover) Install pip dependencies
  pip:
    name:
      - boto3
      - requests
    executable: pip3

- name: (failover) Copy leader election script
  template:
    src: leader-election.py.j2
    dest: /usr/bin/leader-election.py

- name: (failover) Create the leader-election service
  template:
    src: leader-election.service.j2
    dest: /lib/systemd/system/leader-election.service

- name: (failover) Enable and start the leader-election service
  become: yes
  systemd:
    name: leader-election.service
    state: started
    enabled: true
    daemon_reload: yes

- name: (failover) Update slapd service to only start on the primary
  lineinfile:
    path: /lib/systemd/system/slapd.service
    insertbefore: ^ExecStart=*
    line: /bin/curl -sf localhost/is-primary

- name: (failover) Enable auto-restart of slapd service
  blockinfile:
    path: /lib/systemd/system/slapd.service
    insertafter: ^ExecStart=*
    block: |
      RemainAfterExit=yes
      Restart=on-failure
      RestartSec=30
      StartLimitInterval=0

- name: (failover) Reload and restart the service
  become: yes
  service:
    name: slapd.service
    state: restarted
    enabled: true
    daemon_reload: yes
  failed_when: false # Let this fail in case another instance is the primary