---

- name: (failover) Enable creation of lock file in the shared data directory
  lineinfile:
    path: /lib/systemd/system/slapd.service
    regexp: ^ExecStart=*
    line: ExecStart=/usr/bin/flock -n {{ data_file | dirname }}/slapd.lock /usr/sbin/slapd -u ldap -h ${SLAPD_URLS} $SLAPD_OPTIONS

- name: (failover) Enable auto-restart if lock cannot be obtained
  blockinfile:
    path: /lib/systemd/system/slapd.service
    insertafter: ^ExecStart=*
    block: |
      RemainAfterExit=yes
      Restart=always
      RestartSec=30
      StartLimitInterval=0

- name: (failover) Update and restart the service
  become: yes
  service:
    name: slapd.service
    state: restarted
    enabled: true
    daemon_reload: yes