---

- name: (failover) Copy script for electing primary instance
  template:
    src: is-primary.py.j2
    dest: /usr/bin/is-primary.py

- name: (failover) Install python3
  yum:
    name: python3
    state: present

- name: (failover) Install pip dependencies
  pip:
    name:
      - boto3
      - requests
    executable: pip3

- name: (failover) Create the is-primary service
  template:
    src: is-primary.service.j2
    dest: /lib/systemd/system/is-primary.service

- name: (failover) Enable and start the service
  become: yes
  systemd:
    name: is-primary.service
    state: started
    enabled: true
    daemon_reload: yes