---

- name: (failover) Install python3
  yum:
    name: python3
    state: present

- name: (failover) Install pip dependencies
  pip:
    name:
      - boto3
      - requests
    executable: pip3

- name: (failover) Copy leader election script
  template:
    src: leader-election.py.j2
    dest: /usr/bin/leader-election.py

- name: (failover) Create the leader-election service
  template:
    src: leader-election.service.j2
    dest: /lib/systemd/system/leader-election.service

- name: (failover) Enable and start the leader-election service
  become: yes
  systemd:
    name: leader-election.service
    state: started
    enabled: true
    daemon_reload: yes
