---

- name: (import-rbac) Clone RBAC repo locally
  delegate_to: localhost
  run_once: yes
  become: no
  git:
    dest: rbac
    repo: https://github.com/ministryofjustice/hmpps-ndelius-rbac
    version: '{{ ldap_config.rbac_version }}'

- name: (import-rbac) Import schemas
  include: rbac/import_schemas.yml

- name: (import-rbac) Import roles
  include: rbac/import_roles.yml

- name: (import-rbac) Import users/clients
  include: rbac/import_users.yml