---

- name: (service) Install packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openldap
    - openldap-servers
    - openldap-clients

- name: (service) Set slapd args
  template:
    src: slapd.args.j2
    dest: /var/run/openldap/slapd.args
    owner: ldap
    group: ldap
    mode: 0644

- name: (service) Start service on boot
  service:
    name: slapd
    enabled: yes

- name: (service) Restart directory service
  service:
    name: slapd
    state: restarted

- name: (service) Hash the admin password
  shell: 'slappasswd -h {SSHA} -s ${bind_password}'
  environment:
    bind_password: '{{ bind_password }}'
  register: bind_password_hash
