---
# tasks file for hmpps-delius-core-ldap-bootstrap

- name: (main) set tag to indicate deployment
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      ndelius_version: "Deploying - {{ ndelius_version }}"

- name: Create workspace
  file:
    path: '{{ workspace }}'
    state: directory
    mode: 0700
    recurse: yes

- name: Set facts
  include: set-facts.yml

- name: Block LDAP port
  include: port-block.yml

- name: Install directory server
  include: install-service.yml

- name: Copy files
  include: copy-files.yml

- name: Configure directory server
  include: config-service.yml

- name: Import schema
  include: schema.yml

- name: Fetch and parse data for import
  include: fetch-data.yml

- name: Import roles, groups and users
  include: import-data.yml

- name: Create test users
  include: test-users.yml

# TODO:
#- name: Setup replication
#  include: replication.yml

# TODO:
#- name: Add user start/end date handling
#  include: user-expiry.yml

- name: Enable regular backups
  include: backups.yml

- name: Unblock LDAP port
  include: port-unblock.yml

- name: Remove workspace
  file:
    path: '{{ workspace }}'
    state: absent

- name: (main) set tag to indicate deployed ndelius_version
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      ndelius_version: "{{ ndelius_version }}"
