---
# tasks file for hmpps-delius-core-ldap-bootstrap

- name: (main) set tag to indicate deployment
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      ndelius_version: "Deploying - {{ ndelius_version }}"

- name: (main) Create workspace
  file:
    path: '{{ workspace }}'
    state: directory
    mode: 0700
    recurse: yes

- name: Set facts
  include: set-facts.yml

- name: (port) Block inbound access on ldap_port until bootstrap is finished
  iptables:
    chain: INPUT
    protocol: tcp
    source: '!127.0.0.1'
    destination_port: '{{ ldap_port }}'
    jump: REJECT
    state: present
  become: yes

- name: Install OpenLDAP
  include: openldap.yml

- name: Configure monitoring and logging
  include: monitoring.yml

- name: Import delius schemas
  include: schema.yml

- name: Fetch and parse data for import
  include: fetch-data.yml

- name: Import roles, groups and users
  include: import-data.yml

- name: Create test users
  include: test-users.yml

- name: Handle start/end date attributes
  include: user-expiry.yml

- name: Enable replication
  include: replication.yml

- name: Enable regular backups
  include: backups.yml

- name: (main) Remove workspace
  file:
    path: '{{ workspace }}'
    state: absent

- name: (port) Re-enable inbound access on ldap_port
  iptables:
    chain: INPUT
    protocol: tcp
    source: '!127.0.0.1'
    destination_port: '{{ ldap_port }}'
    jump: REJECT
    state: absent
  become: yes

- name: (main) set tag to indicate deployed ndelius_version
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      ndelius_version: "{{ ndelius_version }}"
