---
# tasks file for hmpps-delius-core-ldap-bootstrap

- name: (main) set tag to indicate deployment
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      rbac_version: "Deploying - {{ ldap_config.rbac_version }}"

- name: Set facts
  include: set-facts.yml

- name: (main) Create workspace
  file:
    path: '{{ workspace }}'
    state: directory
    mode: 0700
    recurse: yes

- name: (port) Block inbound access on ldap_port until bootstrap is finished
  iptables:
    chain: INPUT
    protocol: tcp
    source: '!127.0.0.1'
    destination_port: '{{ ldap_port }}'
    jump: REJECT
    state: present
  become: yes

- name: Mount EFS
  when: efs_dns_name is defined and efs_dns_name != ''
  include: efs.yml

- name: Install OpenLDAP
  include: openldap.yml

- name: Install schemas
  include: schemas.yml

- name: Handle start/end date attributes
  include: user-expiry.yml

- name: Configure monitoring and logging
  include: monitoring.yml

- name: Enable failover endpoint
  when: efs_dns_name is defined and efs_dns_name != ''
  include: failover.yml

- name: Enable regular backups
  include: backups.yml

- name: Create ndmis directory and script
  include: mis_scripts.yml

- name: (main) Remove workspace
  file:
    path: '{{ workspace }}'
    state: absent

- name: (port) Re-enable inbound access on ldap_port
  iptables:
    chain: INPUT
    protocol: tcp
    source: '!127.0.0.1'
    destination_port: '{{ ldap_port }}'
    jump: REJECT
    state: absent
  become: yes

- name: (main) set tag to indicate deployed rbac_version
  ec2_tag:
    region: "{{ region }}"
    resource: "{{ instance_id }}"
    state: present
    tags:
      rbac_version: "{{ ldap_config.rbac_version }}"
