---

- name: Create ndmis directory if it does not exist
  file:
    path: /root/ndmis_requests
    state: directory
    mode: '0755'

- name: Create mis user grant script
  template:
    src: add_user_to_group.sh.j2
    dest: /root/ndmis_requests/add_user_to_group.sh
    mode: u+x

- name: Create mis_group_names file
  template:
    src: "{{ role_path }}/templates/mis_group_names.j2"
    dest: "/root/ndmis_requests/group_names"
    owner: "root"
    mode: "0640"
    group: "root"
