---

- name: (openldap) Install packages
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - openldap-servers
    - openldap-clients

- name: (openldap) Set slapd args
  template:
    src: slapd.args.j2
    dest: /etc/sysconfig/slapd
    owner: ldap
    group: ldap
    mode: 0644

- name: (openldap) Remove default hdb database
  file:
    path: '/etc/openldap/slapd.d/cn=config/olcDatabase={2}hdb.ldif'
    state: absent

- name: (openldap) Start service on boot
  service:
    name: slapd
    state: started
    enabled: yes

- name: (openldap) Hash the admin password
  shell: 'slappasswd -h {SSHA} -s ${bind_password}'
  environment:
    bind_password: '{{ bind_password }}'
  register: bind_password_hash

- name: (openldap) Copy db.ldif template
  template:
    src: 'db.ldif.j2'
    dest: '{{ workspace }}/db.ldif'
    mode: 0644

- name: (openldap) Create database
  shell: 'ldapadd -Y EXTERNAL -H ldapi:/// -f {{ workspace }}/db.ldif'

- name: (openldap) Install schemas
  shell: 'ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/{{ item }}'
  with_items:
    - cosine.ldif
    - nis.ldif
    - inetorgperson.ldif
    - java.ldif
