---

- name: (replication) Copy script for updating replicas
  template:
    src: update_replicas.sh.j2
    dest: /usr/bin/update_replicas
    mode: u+x

- name: (replication) Scheduled task to keep replica details up-to-date, every minute
  cron:
    name: Update replica details
    job: update_replicas
    minute: '*'
    hour: '*'
    day: '*'
    month: '*'
    weekday: '*'