---

- name: (replication) Copy script for electing primary instance
  template:
    src: is-primary.py.j2
    dest: /usr/bin/is-primary.py

- name: (replication) Install python3
  yum:
    name: python3
    state: present

- name: (replication) Install pip dependencies
  pip:
    name:
      - boto3
      - requests
    executable: pip3

- name: (replication) Create the is-primary service
  template:
    src: is-primary.service.j2
    dest: /lib/systemd/system/is-primary.service

- name: (replication) Enable and start the service
  become: yes
  systemd:
    name: is-primary.service
    state: started
    enabled: true
    daemon_reload: yes

- name: (replication) Copy script for updating replicas
  template:
    src: update_replicas.sh.j2
    dest: /usr/bin/update_replicas
    mode: u+x

- name: (replication) Scheduled task to keep replica details up-to-date, every minute
  cron:
    name: Update replica details
    job: update_replicas
    minute: '*'
    hour: '*'
    day: '*'
    month: '*'
    weekday: '*'