---

- name: (schema) Import schemas and context
  shell: 'ldapadd -Y EXTERNAL -H ldapi:/// -f {{ workspace }}/{{ item }}'
  environment:
    bind_password: '{{ bind_password }}'
  with_items:
    - schema.ldif
    - pwm-schema.ldif
    - context.ldif
