---

- name: (schemas) Clone RBAC repo locally
  delegate_to: localhost
  run_once: yes
  become: no
  git:
    dest: rbac
    repo: https://github.com/ministryofjustice/hmpps-ndelius-rbac
    version: '{{ ldap_config.rbac_version }}'

- name: (schemas) Import schemas
  include_tasks: rbac/import_schemas.yml