---

- name: (facts) Get hostname
  shell: hostname
  register: hostname

- name: (facts) Set facts
  set_fact:
    workspace: /root/bootstrap-workspace
    bind_user: "{{ bind_user | default('cn=admin,'+base_root) }}"
    data_file: "{{ data_file | default('/var/lib/ldap/data.mdb') }}"
    ldap_connection: '-H ldap:/// -D "cn=root,{{ base_root }}" -w ${bind_password}'

- name: (facts) Get processor count
  shell: grep -c processor /proc/cpuinfo
  register: processor_count

- name: (facts) Get IP address of the current instance
  shell: curl http://169.254.169.254/latest/meta-data/local-ipv4
  register: private_ip
