---

- name: (facts) Get hostname
  shell: hostname
  register: hostname

- name: (facts) Set facts
  set_fact:
    workspace: /root/bootstrap-workspace
    bind_user: "{{ bind_user | default('cn=admin,'+base_root) }}"
    ldap_connection: '-H ldap:/// -D "cn=root,{{ base_root }}" -w ${bind_password}'

- name: (facts) Get processor count
  shell: grep -c processor /proc/cpuinfo
  register: processor_count

- name: (facts) Get IP address of the current instance
  shell: >
    aws ec2 describe-instances --output text --region {{ region }}
    --query 'Reservations[*].Instances[*].[PrivateIpAddress]'
    --instance-ids $INSTANCE_ID
  register: private_ip
