---

- name: (test-users) Create performance test users
  when: perf_test_users|default('0')|int > 0
  shell: 'ldapadd {{ ldap_connection }} -f {{ workspace }}/{{ item.file }}'
  register: create_perf_test_users
  failed_when: create_perf_test_users.rc not in [0,33,68]
  # Allowed return codes:
  # 0=SUCCESS
  # 33=ALIAS_PROBLEM (invalid role association which should be ignored)
  # 68=ENTRY_EXISTS (duplicate entries should be ignored)
  environment:
    bind_password: '{{ bind_password }}'
  with_items:
    - { file: test-users.ldif }