---

- name: (user-expiry) Copy user expiry script
  template:
    src: user_expiry.sh.j2
    dest: /usr/bin/user_expiry
    mode: u+x

- name: (user-expiry) Scheduled task to lock users after end date
  cron:
    name: Expire LDAP users
    job: curl -sf localhost/is-primary && user_expiry
    special_time: "daily"
